spring.application.name=category-service

server.port=${PORT:9095}

#spring.profiles.active=prod

#db configuration

spring.datasource.url=jdbc:mysql://localhost:3309/categorydb
spring.datasource.username=user
spring.datasource.password=user123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost

#actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoints.shutdown.enabled=true
management.info.env.enabled=true
info.app.name={cipher}1275f174df09d486e861a550956d4d1b6b3fb6981acc7ab90d227990988a91d623dc2b7036f5926bc60e35164432382a
info.app.description=This is category service
info.app.version=1.0

