spring:
  application:
    name: course-service

  datasource:
    url: jdbc:postgresql://localhost:5432/coursedb
    username: user
    password: user123
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 9092

#eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
  instance:
    prefer-ip-address: true

#Actuator End[oint cnofiguration
management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: "Course-Service-config server"
    description: "This is Course service"
    version: "1.0"